#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""moc 86 五笔方案生成脚本（从头写）。

从 3 个上游仓库的锁定源生成纯简五笔方案：
  - moc_wubi86_simp      主力，纯极点 core（字+词）
  - moc_wubi86_simp_plus 主力，core + 白霜词组（weight>=20 去重）+ 英文混输

砍掉：Z键双拼补字、mspy 方案、整句、单字优先过滤器。
过滤：去 non-CJK 行、去繁体/异体行（OpenCC t2s）。
不写 ~/Library/Rime，只输出到 dist/。
"""
import sys
import shutil
import math
from collections import Counter
from pathlib import Path

from opencc import OpenCC

ROOT = Path(__file__).resolve().parents[1]          # rime-wubi86-moc/
SRC = ROOT / "work" / "sources"
DIST = ROOT / "dist"
LUA_DIR = DIST / "lua"

# 上游源文件（clone + checkout 后存在）
JIDIAN_DICT = SRC / "rime-wubi86-jidian" / "wubi86_jidian.dict.yaml"
FROST_WORDS = SRC / "rime-frost" / "cn_dicts_wb" / "words.dict.yaml"
FROST_EN = SRC / "rime-frost" / "en_dicts" / "en.dict.yaml"
FROST_EN_EXT = SRC / "rime-frost" / "en_dicts" / "en_ext.dict.yaml"
FROST_PINYIN = SRC / "rime-frost" / "cn_dicts" / "8105.dict.yaml"   # frost 单字+拼音表（反查字典源）
XDHYCYC = ROOT / "work" / "data" / "xdhycyc.txt"   # 《现代汉语常用词表（第2版）》规范现代词源（补五笔词来源）
ZHIHU_FREQ = SRC / "rime-frost" / "others" / "知频.txt"        # 白霜知乎频（补充校准用）
WIKI_FREQ  = SRC / "rime-frost" / "others" / "维基频.txt"      # 白霜维基频（补充校准用）
OH_MY_RIME_LUA = SRC / "oh-my-rime" / "lua"
GB_LEVEL12 = ROOT / "work" / "data" / "gb_level12.txt"        # 通用规范汉字表 一级+二级（白名单主体 ~6500）
GB_LEVEL3_REF = ROOT / "work" / "data" / "gb_level3.txt"      # 三级字表（参考/黑名单，默认删）
PROTECT_CHARS_FILE = ROOT / "work" / "data" / "protect_chars.txt"  # 用户保留的三级字（人名/专业用字，如镕喆）
GOOGLE_20K = ROOT / "work" / "data" / "google_20k.txt"   # first20hours/google-10000-english 频率排名表（行号=排名）

FROST_THRESHOLD = 20          # frost 词组权重阈值
MAX_FREQ_ORDER = 56790             # 现代汉语常用词表最大频序号；weight 校准用（weight = MAX_FREQ_ORDER - 频序号）

ENGLISH_TOP_N = 8000          # 英文主词库按 google 频率保留 top N（en.dict 精选）
# 生僻字保护名单已改为文件 work/data/protect_chars.txt（PROTECT_CHARS_FILE），用户编辑保留三级字
VERSION = "2026-06-29"

cc = OpenCC("t2s")


# ---------- 通用 rime dict 解析/写出 ----------
def parse_header_columns(path):
    """从 dict.yaml header 提取 columns；无则返回 None。"""
    cols, in_header, in_cols = [], False, False
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.rstrip("\n")
            if s.strip() == "---":
                in_header = True
                continue
            if s.strip() == "...":
                break
            if not in_header:
                continue
            if s.startswith("columns:"):
                in_cols = True
                continue
            if in_cols:
                if s.lstrip().startswith("- "):
                    val = s.strip()[2:].strip()
                    if "#" in val:
                        val = val.split("#", 1)[0].strip()
                    cols.append(val)
                else:
                    in_cols = False
    return cols or None


def parse_dict(path):
    """返回 rows: list of (text, code, weight, stem)。weight 为 int。"""
    cols = parse_header_columns(path) or ["text", "code", "weight", "stem"]
    idx = {c: i for i, c in enumerate(cols)}
    rows, in_data = [], False
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.rstrip("\n")
            if not in_data:
                if s.strip() == "...":
                    in_data = True
                continue
            if not s.strip() or s.lstrip().startswith("#"):
                continue
            parts = s.split("\t")
            def get(col, default=""):
                i = idx.get(col)
                return parts[i] if i is not None and i < len(parts) else default
            text = get("text")
            if not text:
                continue
            try:
                w = int(get("weight", "0"))
            except ValueError:
                w = 0
            rows.append((text, get("code"), w, get("stem")))
    return rows


def write_dict(path, name, rows, note):
    """写 moc 风格 dict.yaml：4列 text/code/weight/stem，sort: by_weight。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Rime dictionary\n# encoding: utf-8\n")
        f.write(f"# Generated by work/build_moc_wubi86.py. Do not edit by hand.\n")
        f.write("---\n")
        f.write(f'name: {name}\nversion: "{VERSION}"\nsort: by_weight\n')
        f.write(f"note: '{note}'\n")
        f.write("columns:\n  - text\n  - code\n  - weight\n  - stem\n...\n")
        for text, code, w, stem in rows:
            f.write(f"{text}\t{code}\t{w}\t{stem}\n")


def write_import_dict(path, name, imports, note):
    """写仅含 import_tables 头的聚合 dict（无正文）。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Rime dictionary\n# encoding: utf-8\n")
        f.write(f"# Generated by work/build_moc_wubi86.py. Do not edit by hand.\n")
        f.write("---\n")
        f.write(f'name: {name}\nversion: "{VERSION}"\nsort: by_weight\n')
        f.write(f"note: '{note}'\nimport_tables:\n")
        for t in imports:
            f.write(f"  - {t}\n")
        f.write("...\n")


# ---------- 过滤 ----------
def has_cjk(text):
    return any("一" <= ch <= "鿿" for ch in text)


def has_traditional(text):
    return cc.convert(text) != text


def load_gb8105():
    """白名单 = 通用规范汉字表一级+二级 + 用户 protect_chars。
    三级字默认删（茳等生僻）；用户在 protect_chars.txt 加要保留的三级字（镕喆等人名用字）。"""
    chars = set()
    for fn in (GB_LEVEL12, PROTECT_CHARS_FILE):
        if not fn.exists():
            print(f"警告：缺 {fn.name}", file=sys.stderr); continue
        for line in fn.read_text(encoding="utf-8").splitlines():
            c = line.strip()
            if c and not c.startswith("#"):
                chars.add(c)
    return chars


def load_google_rank():
    """读 google 20k 频率表，返回 {词小写: 排名(1=最常用)}；缺表返回 None（英文不精选）。"""
    if not GOOGLE_20K.exists():
        print(f"[english] 警告：缺 {GOOGLE_20K.name}，英文主表不做频率精选", file=sys.stderr)
        return None
    rank = {}
    for i, w in enumerate(GOOGLE_20K.read_text(encoding="utf-8").splitlines(), 1):
        w = w.strip().lower()
        if w and w not in rank:
            rank[w] = i
    return rank


def load_xdhycyc_freq():
    """现代汉语常用词表 频序号 map {词: 频序号}（频序号越小越常用）。多音字取最小频序号（最常用读音）。"""
    freq = {}
    with open(XDHYCYC, encoding="utf-8") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) >= 3 and p[0] != "词语":
                try: fo = int(p[-1])
                except ValueError: continue
                if p[0] not in freq or fo < freq[p[0]]:
                    freq[p[0]] = fo
    return freq


# 知乎/维基频 log10 映射参数（经验值，覆盖范围约 1 ~ 3.2×10⁷）
_LOG_FREQ_MAX = 7.5          # log10(维基频最大值) 经验上限
_ZHIHU_WEIGHT_MIN = 200      # 知乎/维基频校准保底 weight
_ZHIHU_WEIGHT_MAX = 30000    # 知乎/维基频校准上限 weight
# 两源加权融合：知乎（问答社区，接近打字场景）权重高于维基（百科，偏向阅读）
_ZHIHU_RATIO = 0.7
_WIKI_RATIO = 0.3


def load_zhihu_wiki_freq():
    """分别加载知乎频和维基频，返回 (zhihu, wiki) 两个 {词: 频数}。
    不再取 max——两源语料性质不同（知乎=讨论/打字，维基=百科/阅读），
    交给 calibrate_weight 分别 log 映射后加权融合，避免维基频让专有名词畸高。"""
    zhihu, wiki = {}, {}
    for path, target in ((ZHIHU_FREQ, zhihu), (WIKI_FREQ, wiki)):
        if not path.exists():
            print(f"[calibrate] 警告：缺 {path.name}，跳过", file=sys.stderr)
            continue
        with open(path, encoding="utf-8") as f:
            for line in f:
                p = line.rstrip("\n").split("\t")
                if len(p) < 2:
                    continue
                text, count_s = p[0], p[1]
                try:
                    count = int(count_s)
                except ValueError:
                    continue
                if text not in target or count > target[text]:
                    target[text] = count
    return zhihu, wiki


def _zhihu_weight(count):
    """将知乎/维基频原始频数映射到 [_ZHIHU_WEIGHT_MIN, _ZHIHU_WEIGHT_MAX]。"""
    if count <= 0:
        return _ZHIHU_WEIGHT_MIN
    log_f = math.log10(count)
    # 线性映射：log_f=0 → _ZHIHU_WEIGHT_MIN, log_f=_LOG_FREQ_MAX → _ZHIHU_WEIGHT_MAX
    w = _ZHIHU_WEIGHT_MIN + (log_f / _LOG_FREQ_MAX) * (_ZHIHU_WEIGHT_MAX - _ZHIHU_WEIGHT_MIN)
    return int(max(_ZHIHU_WEIGHT_MIN, min(_ZHIHU_WEIGHT_MAX, w)))


def load_jidian_raw_weight():
    """加载极点原表的原始 weight，返回 {(text, code): raw_weight}。
    用于在知乎/维基频校准后，按编码内极点经验做二次微调。"""
    weights = {}
    with open(JIDIAN_DICT, encoding="utf-8") as f:
        in_data = False
        for line in f:
            s = line.rstrip("\n")
            if not in_data:
                if s.strip() == "...":
                    in_data = True
                continue
            if not s.strip() or s.lstrip().startswith("#"):
                continue
            parts = s.split("\t")
            if len(parts) >= 3:
                text, code = parts[0], parts[1].lower()
                try:
                    w = int(parts[2])
                except ValueError:
                    w = 0
                key = (text, code)
                # 同一 text+code 取最大 weight（去重）
                if key not in weights or w > weights[key]:
                    weights[key] = w
    return weights


# RRF（Reciprocal Rank Fusion）排名融合参数
# 两个信号各自排名后按 1/(k+rank) 求和融合，消除桶化方案的盲区
_RRF_K = 60                  # RRF 平滑常数（信息检索经典值，IEEE 2009）
_RRF_JIDIAN_W = 2.0          # 极点信号权重（>1：极点为五笔打字场景专门标注，比通用语料更相关）
_RRF_BASE = 40000            # 非简码词组内最高 weight（低于二级简码 80000，按组内位置递减）
_JIDIAN_SIGNAL_MIN = 10      # 极点 raw weight 阈值：≤此值视为无信号（极点表 77171/89265 条是默认值 10，无区分度）

# 一级简码从极点原表动态提取（load_jidian_1char）。
# 不硬编码：极点原表 b 键 top1 是"了"而非官方字根表的"子"，实用场景"了"更常用。
# 25 个键中 24 个与官方表一致，仅 b 不同——尊重极点（成熟方案）与用户习惯。
_JIANMA_FALLBACK = {
    'a': '工', 'b': '了', 'c': '以', 'd': '在', 'e': '有', 'f': '地',
    'g': '一', 'h': '上', 'i': '不', 'j': '是', 'k': '中', 'l': '国',
    'm': '同', 'n': '民', 'o': '为', 'p': '这', 'q': '我', 'r': '的',
    's': '要', 't': '和', 'u': '产', 'v': '发', 'w': '人', 'x': '经',
    'y': '主',
}
_JIANMA_WEIGHT = 99999      # 一级简码固定最高 weight
_JIANMA2_WEIGHT = 80000     # 二级简码固定高 weight（低于一级，高于任何 RRF 映射）


def load_jidian_1char():
    """从极点原表提取一级简码（单字母编码）的最高 weight 候选。
    返回 {code: text}。极点原表缺某键时回落到 _JIANMA_FALLBACK。

    实测：25 个键中 24 个与官方五笔86字根表一致，仅 b 不同（极点"了" vs 官方"子"），
    "了"是超高频虚词，尊重极点的实际选择。"""
    best = {}
    with open(JIDIAN_DICT, encoding="utf-8") as f:
        in_data = False
        for line in f:
            s = line.rstrip("\n")
            if not in_data:
                if s.strip() == "...":
                    in_data = True
                continue
            if not s.strip() or s.lstrip().startswith("#"):
                continue
            parts = s.split("\t")
            if len(parts) >= 3 and len(parts[1]) == 1:
                text, code = parts[0], parts[1].lower()
                try:
                    w = int(parts[2])
                except ValueError:
                    w = 0
                if code not in best or w > best[code][1]:
                    best[code] = (text, w)
    extracted = {code: text for code, (text, _) in best.items()}
    # 极点缺某键时回落到 fallback（确保 25 个键齐全）
    for code, text in _JIANMA_FALLBACK.items():
        extracted.setdefault(code, text)
    return extracted


def load_jidian_2char():
    """从极点原表提取二级简码（双字母编码）的最高 weight 候选。
    返回 {code: text}。

    局限：极点原表双字母编码 94% weight=10，作者未刻意标注二级简码，
    提取结果正确性依赖极点表的成熟度（实测 88% 频数≥1000）。
    理想方案应替换为标准五笔86二级简码表，但当前无权威源。"""
    best = {}
    with open(JIDIAN_DICT, encoding="utf-8") as f:
        in_data = False
        for line in f:
            s = line.rstrip("\n")
            if not in_data:
                if s.strip() == "...":
                    in_data = True
                continue
            if not s.strip() or s.lstrip().startswith("#"):
                continue
            parts = s.split("\t")
            if len(parts) >= 3 and len(parts[1]) == 2:
                text, code = parts[0], parts[1].lower()
                try:
                    w = int(parts[2])
                except ValueError:
                    w = 0
                if code not in best or w > best[code][1]:
                    best[code] = (text, w)
    return {code: text for code, (text, _) in best.items()}


def calibrate_weight(rows, xdhycyc_freq, zhihu_freq, wiki_freq, jidian_raw, jidian_1char, jidian_2char):
    """RRF 双信号排名融合校准：
    1) 一/二级简码固定高 weight（肌肉记忆硬规则；均从极点原表动态提取）；
    2) 其余词按编码分组，组内对两个信号各自排名：
       - 频数信号（知乎/维基频加权融合，常用词表/保底为辅）
       - 极点信号（极点原表 raw weight；frost 词无此信号则该项缺省）
    3) score = 1/(_RRF_K+rank_freq) + _RRF_JIDIAN_W × 1/(_RRF_K+rank_jidian)；
    4) 组内按 (score, 极点 raw weight) 排序赋唯一递减 weight，极点做 tie-break。

    频数信号：知乎/维基分别 log 映射后按 _ZHIHU_RATIO/_WIKI_RATIO 加权，
    避免维基频让百科专有名词（如"拿破仑"）畸高压过日常词（如"优化"）。
    """
    from collections import defaultdict

    # 第一遍：算 base / jidian_w / 简码标记
    items = []
    for idx, (text, code, w, stem) in enumerate(rows):
        code_l = code.lower()
        is_jm1 = code_l in jidian_1char and text == jidian_1char[code_l]
        is_jm2 = code_l in jidian_2char and text == jidian_2char[code_l]
        zw = _zhihu_weight(zhihu_freq[text]) if text in zhihu_freq else None
        ww = _zhihu_weight(wiki_freq[text]) if text in wiki_freq else None
        if zw is not None and ww is not None:
            base = int(_ZHIHU_RATIO * zw + _WIKI_RATIO * ww)
        elif zw is not None:
            base = zw
        elif ww is not None:
            base = ww
        elif text in xdhycyc_freq:
            base = MAX_FREQ_ORDER - xdhycyc_freq[text]
        else:
            base = max(100, w)
        jw_raw = jidian_raw.get((text, code_l))
        # 极点默认值 w=10 无区分度（占 86%），视为无信号，避免"碰巧有条目"的词拿到 bonus
        jw = jw_raw if (jw_raw is not None and jw_raw > _JIDIAN_SIGNAL_MIN) else None
        items.append([idx, text, code, stem, base, jw, is_jm1, is_jm2])

    # 按编码分组，组内 RRF
    groups = defaultdict(list)
    for it in items:
        groups[it[2].lower()].append(it)
    for code_l, grp in groups.items():
        n = len(grp)
        # rank_freq：按 base 降序，0=最常用
        order_f = sorted(range(n), key=lambda i: -grp[i][4])
        rank_f = [0] * n
        for r, i in enumerate(order_f):
            rank_f[i] = r
        # rank_jidian：仅对有极点信号的词排名
        has_jw = [i for i in range(n) if grp[i][5] is not None]
        order_j = sorted(has_jw, key=lambda i: -grp[i][5])
        rank_j = {}
        for r, i in enumerate(order_j):
            rank_j[i] = r
        # RRF 融合分数
        for i in range(n):
            s = 1.0 / (_RRF_K + rank_f[i])
            if i in rank_j:
                s += _RRF_JIDIAN_W * 1.0 / (_RRF_K + rank_j[i])
            grp[i].append(s)
        # 组内按 (score 降序, 极点 raw weight 降序) 排序，赋唯一递减 weight
        # 极点 raw weight 作为 tie-break：RRF 平局时尊重极点经验
        order = sorted(range(n), key=lambda i: (-grp[i][8], -(grp[i][5] or 0)))
        for pos, i in enumerate(order):
            grp[i].append(pos)  # grp[i][9] = 组内位置

    # 赋最终 weight（保留原始行顺序）
    # 非简码词：weight = 40000 - 组内位置，保证同编码内递减且唯一，绝对值低于简码保护
    out = [None] * len(rows)
    for it in items:
        idx, text, code, stem, base, jw, is_jm1, is_jm2, score, pos = it
        if is_jm1:
            final_w = _JIANMA_WEIGHT
        elif is_jm2:
            final_w = _JIANMA2_WEIGHT
        else:
            final_w = _RRF_BASE - pos
        out[idx] = (text, code, final_w, stem)
    return out


def filter_wubi_rows(rows, drop_weights_below=None, exclude_texts=None, exclude_keys=None, whitelist=None):
    """五笔候选过滤：去 non-CJK、去繁体/异体、去生僻字(不在白名单)；可选权重阈值与去重。

    去重两种模式：
    - exclude_texts：按 text 全局去重（不管编码）
    - exclude_keys：按 (text, code.lower()) 去重，保留同 text 不同 code 的合法编码变体

    生僻字规则：单字不在 8105 白名单 -> 删；词组任一汉字不在 -> 整词删。
    非汉字字符（数字/字母）不触发白名单检查。
    """
    exclude_texts = exclude_texts or set()
    exclude_keys = exclude_keys or set()
    kept, n_ncjk, n_trad, n_rare, n_weight, n_dup = [], 0, 0, 0, 0, 0
    for text, code, w, stem in rows:
        if not has_cjk(text):
            n_ncjk += 1
            continue
        if has_traditional(text):
            n_trad += 1
            continue
        if whitelist is not None and any(c not in whitelist for c in text if has_cjk(c)):
            n_rare += 1
            continue
        if drop_weights_below is not None and w < drop_weights_below:
            n_weight += 1
            continue
        if text in exclude_texts or (text, code.lower()) in exclude_keys:
            n_dup += 1
            continue
        kept.append((text, code, w, stem))
    return kept, dict(non_cjk=n_ncjk, traditional=n_trad, rare=n_rare,
                      low_weight=n_weight, dup=n_dup)


# ---------- 各表生成 ----------
def gen_core_rows(whitelist):
    """过滤极点 core，返回未 calibrate 的 rows。calibrate 在合并后统一做（RRF 需跨表分组）。"""
    rows = parse_dict(JIDIAN_DICT)
    kept, stat = filter_wubi_rows(rows, whitelist=whitelist)
    print(f"[core] 源 {len(rows)} -> 保留 {len(kept)}  过滤 {stat}")
    return kept


def gen_frost_words_rows(core_rows, whitelist):
    """过滤白霜 frost（去重 vs core），返回未 calibrate 的 rows。

    去重按 (text, code)：core 已收录的精确 (text,code) 才跳过，
    同 text 不同 code 的编码变体保留（如 frost 给的成语另一种五笔码），
    让用户打任一编码都能出词，候选层由 rime uniquifier 去重。"""
    core_keys = {(r[0], r[1].lower()) for r in core_rows}
    rows = parse_dict(FROST_WORDS)
    kept, stat = filter_wubi_rows(rows, drop_weights_below=FROST_THRESHOLD,
                                  exclude_keys=core_keys, whitelist=whitelist)
    print(f"[frost_words] 源 {len(rows)} -> 保留 {len(kept)}  过滤 {stat}")
    return kept


def gen_english():
    """英文辅助：en.dict 按 google 频率 top N 精选；en_ext 专有名词保留。编码小写、候选原形。"""
    artefacts = (".ds_store", "&nbsp;", "<", ">", "http", "//")
    rank = load_google_rank()
    seen, kept, n_skip = set(), [], 0

    def push(text, code, w, stem):
        nonlocal n_skip
        code_l = code.lower()
        if not code_l or not any(c.isalpha() for c in code_l):
            n_skip += 1; return
        if text.lower() in artefacts or any(a in text.lower() for a in artefacts):
            n_skip += 1; return
        key = (code_l, text)
        if key in seen:
            n_skip += 1; return
        seen.add(key); kept.append((text, code_l, w, stem))

    en_rows = parse_dict(FROST_EN)
    n_freq = 0
    for text, code, w, stem in en_rows:
        if rank is not None and rank.get(text.lower(), 10**9) > ENGLISH_TOP_N:
            n_freq += 1; continue
        push(text, code, w, stem)
    ext_rows = parse_dict(FROST_EN_EXT)
    for text, code, w, stem in ext_rows:
        push(text, code, w, stem)
    write_dict(DIST / "moc_english_words.dict.yaml", "moc_english_words", kept,
               f"frost en(top{ENGLISH_TOP_N} by google freq)+en_ext, lowercase code, original-case text")
    print(f"[english] en {len(en_rows)}(频率筛掉 {n_freq}) + en_ext {len(ext_rows)} -> 保留 {len(kept)}  其他跳过 {n_skip}")
    return kept


def gen_reverse():
    """拼音反查字典（frost 8105 单字+拼音）+ 配套 schema。

    reverse_lookup 引用的字典不会被 --build 自动编译 prism，
    需配套一个 visible:false 的拼音 schema 注册到 schema_list，
    --build 才会编译出 prism，reverse_lookup_translator 才能匹配拼音。
    """
    rows = parse_dict(FROST_PINYIN)
    kept = [(t, c, w, s) for t, c, w, s in rows if len(t) == 1]
    write_dict(DIST / "moc_reverse.dict.yaml", "moc_reverse", kept,
               "frost 8105 单字+拼音，拼音反查字典")
    (DIST / "moc_reverse.schema.yaml").write_text(
        f'''# Rime schema
# encoding: utf-8
# moc 拼音反查字典配套 schema（visible:false，仅 --build 编译 prism 用，不显示在菜单）
schema:
  schema_id: moc_reverse
  name: "moc 拼音反查字典"
  version: "{VERSION}"
  visible: false
engine:
  translators:
    - table_translator
speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
translator:
  dictionary: moc_reverse
''', encoding="utf-8")
    print(f"[reverse] {len(kept)} 单字 -> moc_reverse.dict.yaml + .schema.yaml")


# ---------- lua ----------
LUA_COPY = [
    "number_translator.lua",                # 金额大写（R+数字），oh-my-rime 上游原生
    "chineseLunarCalendar_translator.lua",  # 农历（N+日期），oh-my-rime 上游原生
]

# 日期/时间、计算器：oh-my-rime 原版分别用 o 键、小写功能键引导，与五笔字根冲突。
# 从头写极简版，用 / 前缀引导（/rq /sj /calc），不与小写五笔编码冲突。
DATE_TIME_LUA = (
    "-- moc 日期/时间（从头写）：/rq 日期、/sj 时间。斜杠引导，不与五笔字根冲突。\n"
    "local function translator(input, seg, env)\n"
    "    if input == \"/rq\" then\n"
    "        yield(Candidate(input, seg.start, seg._end, os.date(\"%Y-%m-%d\"), \"日期\"))\n"
    "        yield(Candidate(input, seg.start, seg._end, os.date(\"%Y年%m月%d日\"), \"日期\"))\n"
    "    elseif input == \"/sj\" then\n"
    "        yield(Candidate(input, seg.start, seg._end, os.date(\"%H:%M\"), \"时间\"))\n"
    "        yield(Candidate(input, seg.start, seg._end, os.date(\"%H:%M:%S\"), \"时间\"))\n"
    "    end\n"
    "end\n"
    "return translator\n"
)

CALCULATOR_LUA = (
    "-- moc 计算器（从头写）：/calc1+2 -> 3，仅四则运算与括号。斜杠引导，不与五笔冲突。\n"
    "local function translator(input, seg, env)\n"
    "    local expr = input:match(\"^/calc([-+*/().%d]+)$\")\n"
    "    if not expr then return end\n"
    "    local ok, result = pcall(load(\"return \" .. expr))\n"
    "    if ok and type(result) == \"number\" then\n"
    "        yield(Candidate(input, seg.start, seg._end, tostring(result), \"计算\"))\n"
    "    else\n"
    "        yield(Candidate(input, seg.start, seg._end, expr, \"解析失败\"))\n"
    "    end\n"
    "end\n"
    "return translator\n"
)

CLEAR_EMPTY_LUA = (
    "-- moc 无候选上屏（从头写）：当前输入无候选时，空格/回车把原始字母上屏。\n"
    "-- 词表外词（如 openclaw）打全后空格上屏；打错编码按 Esc 清空（express_editor 默认）。有候选交 selector。\n"
    "local function processor(key, env)\n"
    "    if key:release() or key:alt() or key:ctrl() or key:super() then return 2 end\n"
    "    local ctx = env.engine.context\n"
    "    if ctx.input == \"\" or ctx:has_menu() then return 2 end\n"
    "    local r = key:repr()\n"
    "    if r == \"space\" or r == \"Return\" then\n"
    "        env.engine:commit_text(ctx.input)\n"
    "        ctx:clear()\n"
    "        return 1\n"
    "    end\n"
    "    return 2\n"
    "end\n"
    "return processor\n"
)

def copy_lua():
    LUA_DIR.mkdir(parents=True, exist_ok=True)
    n = 0
    for name in LUA_COPY:
        s = OH_MY_RIME_LUA / name
        if not s.exists():
            print(f"[lua] 警告：缺 {name}", file=sys.stderr)
            continue
        shutil.copy(s, LUA_DIR / name)
        n += 1
    (LUA_DIR / "moc_date_time.lua").write_text(DATE_TIME_LUA, encoding="utf-8")
    (LUA_DIR / "moc_calculator.lua").write_text(CALCULATOR_LUA, encoding="utf-8")
    (LUA_DIR / "moc_clear_empty.lua").write_text(CLEAR_EMPTY_LUA, encoding="utf-8")
    print(f"[lua] 复制 {n} 个上游 + 写 3 个自写 -> {LUA_DIR.relative_to(ROOT)}/")


# ---------- schema / 方案组装 ----------
SCHEMA_HEADER = """# Rime schema
# encoding: utf-8
# Generated by work/build_moc_wubi86.py. Do not edit by hand.

schema:
  schema_id: {id}
  name: "{name}"
  version: "{version}"
  author:
    - "moc local package, from pinned upstream sources"
  description: |
    {desc}

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中, En ]
  - name: full_shape
    reset: 0
    states: [ 半角, 全角 ]
  - name: ascii_punct
    reset: 0
    states: [ 。，, ．， ]

ascii_composer:
  good_old_caps_lock: true   # CapsLock 仅切换大小写（不主动切中英）；中英切换交给 Caps_Lock
  switch_key:
    Caps_Lock: clear          # CapsLock 按下：清空当前编码 + 切英文，大写字母直接上屏（同 frost 上游）
    Shift_L: commit_text      # 左 Shift：提交候选 + 切中英
    Shift_R: commit_text      # 右 Shift：提交候选 + 切中英
    Control_L: noop
    Control_R: noop

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - lua_processor@*moc_clear_empty
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator
    - reverse_lookup_translator
    - lua_translator@*moc_date_time
    - lua_translator@*moc_calculator
    - lua_translator@*number_translator
    - lua_translator@*chineseLunarCalendar_translator
  filters:
    - uniquifier

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcbaABCDEFGHIJKLMNOPQRSTUVWXYZ/;.
  initials: zyxwvutsrqponmlkjihgfedcbaABCDEFGHIJKLMNOPQRSTUVWXYZ/
  delimiter: " '"
  max_code_length: 32
  auto_clear: max_length

translator:
  dictionary: {dict}
  initial_quality: 1.2
  enable_charset_filter: true
  enable_completion: true
  enable_sentence: false
  enable_user_dict: false
  enable_encoder: false
  encode_commit_history: false

reverse_lookup:
  dictionary: moc_reverse
  prefix: "`"
  tips: "〔拼音反查〕"
  enable_completion: true

punctuator:
  import_preset: default
  symbols:
    "/fh": [ "，", "。", "、", "；", "：", "？", "！", "《》", "（）", "【】" ]

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "^`[a-z]*'?$"
    date: "^/(rq|sj)$"
    calculator: "^/calc[-+*/().0-9]+$"
    rmb: "^R[0-9]+[.]?[0-9]*$"
    gregorian_to_lunar: "^N[0-9]{{1,8}}$"
    punct: "^/fh$"

key_binder:
  import_preset: default

menu:
  page_size: 6
"""


def write_schema(path, schema_id, name, desc, dictionary):
    path.parent.mkdir(parents=True, exist_ok=True)
    text = SCHEMA_HEADER.format(
        id=schema_id, name=name, version=VERSION, desc=desc, dict=dictionary)
    path.write_text(text, encoding="utf-8")


def gen_user_templates():
    """空壳用户词表：用户手填，运行时不写回。user 带格式示例注释。"""
    write_dict(DIST / "moc_wubi86_user.dict.yaml", "moc_wubi86_user", [], "长期个人词条，手填")
    with open(DIST / "moc_wubi86_user.dict.yaml", "a", encoding="utf-8") as f:
        f.write("# 格式：文本<Tab>编码<Tab>权重<Tab>词性（Tab 分隔；# 行 rime 忽略）\n")
        f.write("#\n")
        f.write("# 权重参考（校准后的 scale）：一级简码=99999，二级简码=80000，普通词≈30000-40000。\n")
        f.write("# 个人词条想排第一位，权重填 50000 以上（高于二级简码，低于一级）。\n")
        f.write("# 示例（照格式加自己的词条，删除 # 或新增行）：\n")
        f.write("# 浮亏\tiefn\t50000\t\n")
        f.write("# 张三\tta\t50000\t\n")


def gen_schemes():
    # simp：纯净（纯 core，无英文混输/补充词）
    write_schema(DIST / "moc_wubi86_simp.schema.yaml",
                 "moc_wubi86_simp", "moc 极点86五笔-纯净",
                 "纯极点 core，字+词，简体，不学习（纯净五笔，无英文混输/补充词）。", "moc_wubi86_simp")
    write_import_dict(DIST / "moc_wubi86_simp.dict.yaml", "moc_wubi86_simp",
                      ["moc_wubi86_user", "moc_wubi86_core"],
                      "simp 聚合：user + core（纯净）")
    # simp_plus：丰富（core + frost + 英文）
    write_schema(DIST / "moc_wubi86_simp_plus.schema.yaml",
                 "moc_wubi86_simp_plus", "moc 极点86五笔-全功能",
                 "core + 白霜词组 + 英文混输，简体，不学习（丰富全功能）。", "moc_wubi86_simp_plus")
    write_import_dict(DIST / "moc_wubi86_simp_plus.dict.yaml", "moc_wubi86_simp_plus",
                      ["moc_wubi86_user", "moc_wubi86_core", "moc_wubi86_frost_words", "moc_english_words"],
                      "simp_plus 聚合：user + core + frost_words + 英文混输")
    # default.custom 样例
    gen_default_samples()
    print("[schemes] 生成 simp / simp_plus / default samples")


# default.custom.yaml 模板：注册双方案 + 常用键位（清空重部署时 deploy.sh 直接拷用）
DEFAULT_CUSTOM = """# moc 86 五笔方案注册 + 常用键位（分号选2 / 单引号选3 / 方括号翻页 / Shift 切中英 / Shift+Ctrl+0 方案切换）
patch:
  schema_list:
    - schema: moc_wubi86_simp
    - schema: moc_wubi86_simp_plus
    - schema: moc_reverse       # 反查字典配套（visible:false，仅编译 prism 用）

  switcher:
    hotkeys:
      - "Shift+Control+0"
    abbreviate_options: true
    caption: "【输入法设置】"
    option_list_separator: "｜"

  key_binder:
    bindings:
      - { when: has_menu, accept: semicolon, send: 2 }
      - { when: has_menu, accept: apostrophe, send: 3 }
      - { when: has_menu, accept: bracketleft, send: Page_Up }
      - { when: has_menu, accept: bracketright, send: Page_Down }
      - { accept: Shift_L, toggle: ascii_mode }
"""


def gen_default_samples():
    (DIST / "default.custom.yaml").write_text(DEFAULT_CUSTOM, encoding="utf-8")


# ---------- Squirrel 前端外观 ----------
# 来源：用户备份 ~/Desktop/我的rime备份/squirrel.custom.yaml，原样固化（精简纯教学注释）。
# 全局配置：部署到 ~/Library/Rime/squirrel.custom.yaml，影响所有方案（不止 moc）。
SQUIRREL_CUSTOM = """# Squirrel（鼠须管）前端外观自定义
# encoding: utf-8
# Generated by work/build_moc_wubi86.py. Do not edit by hand.
# 玫枫 Roseo Maple 皮肤（亮/暗随系统切换）+ 指定程序默认英文模式。

patch:
  style:
    color_scheme: roseo_maple
    color_scheme_dark: roseo_maple_dark
  preset_color_schemes:
    roseo_maple:
      name: 玫枫 / Roseo Maple
      candidate_format: "[label]. [candidate] [comment]"
      candidate_list_layout: linear
      text_orientation: horizontal
      status_message_type: mix
      memorize_size: true

      alpha: 1.0
      border_height: 0
      border_width: 0
      border_color: 0xffffff
      back_color: 0xF4F4F6
      corner_radius: 5

      font_point: 18
      line_spacing: 5
      base_offset: 0
      preedit_back_color: 0x364572

      hilited_corner_radius: 5
      hilited_candidate_text_color: 0x4F11FA
      hilited_candidate_back_color: 0xEDEDF9
      hilited_candidate_label_color: 0x884F11FA

      label_font_face: PingFang SC
      label_font_point: 17
      label_color: 0xaaaaaa

      candidate_text_color: 0x222222
      candidate_font_face: PingFang SC
      candidate_font_point: 16

      comment_font_face: PingFang SC
      comment_font_point: 16
      comment_text_color: 0x5AC461

      inline_preedit: true
      spacing: 5
      hilited_text_color: 0x8E8E93
      hilited_back_color: 0xEFEFF4

    roseo_maple_dark:
      name: 玫枫-暗黑 / Roseo Maple Dark
      candidate_format: "[label]. [candidate] [comment]"
      candidate_list_layout: linear
      text_orientation: horizontal
      status_message_type: mix
      memorize_size: true

      alpha: 1.0
      border_height: 1
      border_width: 1
      border_color: 0x444444
      back_color: 0x333333
      corner_radius: 5

      font_point: 18
      line_spacing: 5
      base_offset: 0
      preedit_back_color: 0x364572

      hilited_corner_radius: 5
      hilited_candidate_text_color: 0xffffff
      hilited_candidate_back_color: 0x00ffffff
      hilited_candidate_label_color: 0x5AC461

      label_font_face: PingFang SC
      label_font_point: 17
      label_color: 0x77ffffff

      candidate_text_color: 0x99ffffff
      candidate_font_face: PingFang SC
      candidate_font_point: 16

      comment_font_face: PingFang SC
      comment_font_point: 16
      comment_text_color: 0x5AC461

      inline_preedit: true
      spacing: 5
      hilited_text_color: 0x8E8E93
      hilited_back_color: 0xEFEFF4

  app_options:
    com.apple.Terminal:
      ascii_mode: true
    org.electerm.electerm:
      ascii_mode: true
    com.jetbrains.pycharm:
      ascii_mode: true
"""


def gen_squirrel():
    (DIST / "squirrel.custom.yaml").write_text(SQUIRREL_CUSTOM, encoding="utf-8")
    print("[squirrel] 玫枫皮肤 + app_options -> dist/squirrel.custom.yaml")


# ---------- 部署指南 ----------
INSTALL_MD = """# moc 86 五笔方案 — 部署指南

纯简 86 五笔，双方案（simp 纯净 / simp_plus 丰富）+ 中英混输 + 拼音反查 + 玫枫皮肤。

## 一键部署（项目根）

```bash
bash install.sh
```

清空 `~/Library/Rime` → 全量拷贝 dist → 自动编译字典（含反查 prism）→ 切换到 `moc_wubi86_simp` 或 `moc_wubi86_simp_plus` 即可。

⚠ 手填的 `moc_wubi86_user.dict.yaml` 会被清空重置，需保留先备份。

## 文件清单

| 文件 | 作用 |
|---|---|
| `moc_wubi86_core.dict.yaml` | 极点核心 字+词（简体+去三级+weight校准） |
| `moc_wubi86_frost_words.dict.yaml` | 白霜词组（simp_plus） |
| `moc_english_words.dict.yaml` | 英文词（simp_plus 混输） |
| `moc_reverse.dict.yaml` | 拼音反查字典（反引号+拼音出字+五笔编码） |
| `moc_wubi86_simp.schema/dict.yaml` | 简单：纯 core |
| `moc_wubi86_simp_plus.schema/dict.yaml` | 丰富：core + frost + 英文 |
| `moc_wubi86_user.dict.yaml` | 个人词条空壳（手填） |
| `lua/*.lua` | 日期/计算器/金额/农历/无候选上屏 |
| `squirrel.custom.yaml` | 玫枫皮肤 + app 默认英文（全局） |
| `default.custom.yaml` | 方案注册 + 键位（分号选2/方括号翻页/Shift切中英） |

## 手填个人词条

编辑 `~/Library/Rime/moc_wubi86_user.dict.yaml`，格式 `文本<Tab>编码<Tab>权重<Tab>`。

## 说明
- `squirrel.custom.yaml` 是 Squirrel 前端全局配置，影响所有方案（不止 moc）。
- 字典不学习（enable_user_dict 等 false）。
"""


def gen_install():
    (DIST / "INSTALL.md").write_text(INSTALL_MD, encoding="utf-8")
    print("[install] 部署指南 -> dist/INSTALL.md")


# ---------- 全量部署脚本 ----------
DEPLOY_SH = """#!/usr/bin/env bash
# moc 86 五笔全量部署脚本（清空 ~/Library/Rime 后运行此脚本）
# 会覆盖同名文件；手填的 user 词表会被重置为空壳——如需保留请先备份。
set -e
D="$(cd "$(dirname "$0")" && pwd)"      # 本脚本所在 dist 目录
R=~/Library/Rime
rm -rf "$R"                              # 清空整个 ~/Library/Rime（手填 user.dict 会丢，需保留先备份）
mkdir -p "$R"
cp -R "$D/." "$R/"                        # 全量拷贝：schema/dict/lua/squirrel/default.custom.yaml/user 词表

# 自动编译字典（含 moc_reverse 反查 prism），免去手动点「重新部署」
DEP="/Library/Input Methods/Squirrel.app/Contents/MacOS/rime_deployer"
SH="/Library/Input Methods/Squirrel.app/Contents/SharedSupport"
if [ -x "$DEP" ]; then
    "$DEP" --build "$R" "$SH" && echo "✓ 已编译字典（含反查 prism）"
else
    echo "⚠ 未找到 Squirrel rime_deployer，请鼠须管菜单点「重新部署」"
fi

echo "✓ 已部署到 $R"
echo "→ 切换到 moc_wubi86_simp 或 moc_wubi86_simp_plus 即可。"
"""


def gen_deploy():
    p = DIST / "deploy.sh"
    p.write_text(DEPLOY_SH, encoding="utf-8")
    p.chmod(0o755)
    print("[deploy] 全量部署脚本 -> dist/deploy.sh")


def main():
    for p in [JIDIAN_DICT, FROST_WORDS, FROST_EN, FROST_EN_EXT, GB_LEVEL12, PROTECT_CHARS_FILE, XDHYCYC]:
        if not p.exists():
            print(f"错误：缺少源文件 {p}", file=sys.stderr)
            sys.exit(1)
    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True, exist_ok=True)
    gb = load_gb8105()
    xdhycyc_freq = load_xdhycyc_freq()
    zhihu_freq, wiki_freq = load_zhihu_wiki_freq()
    jidian_raw = load_jidian_raw_weight()
    jidian_1char = load_jidian_1char()
    jidian_2char = load_jidian_2char()
    print(f"== moc 86 五笔生成（frost weight>={FROST_THRESHOLD}, GB一二级白名单 {len(gb)} 字, "
          f"常用词表校准 {len(xdhycyc_freq)} 词, 知乎频 {len(zhihu_freq)}/维基频 {len(wiki_freq)}, "
          f"极点经验 {len(jidian_raw)} 条, 一/二级简码 {len(jidian_1char)}/{len(jidian_2char)}）==")
    core_kept = gen_core_rows(gb)
    frost_kept = gen_frost_words_rows(core_kept, gb)
    # RRF 需跨 core+frost 统一分组，合并后统一 calibrate，再拆回各表
    n_core = len(core_kept)
    calibrated = calibrate_weight(core_kept + frost_kept, xdhycyc_freq, zhihu_freq, wiki_freq, jidian_raw, jidian_1char, jidian_2char)
    core_cal, frost_cal = calibrated[:n_core], calibrated[n_core:]
    write_dict(DIST / "moc_wubi86_core.dict.yaml", "moc_wubi86_core", core_cal,
               "filtered 86 jidian core, simplified, GB一二级, RRF calibrated (知乎/维基频+极点经验)")
    write_dict(DIST / "moc_wubi86_frost_words.dict.yaml", "moc_wubi86_frost_words", frost_cal,
               f"frost wubi words, weight>={FROST_THRESHOLD}, dedup vs core, GB一二级, RRF calibrated")
    gen_reverse()
    gen_english()
    copy_lua()
    gen_user_templates()
    gen_schemes()
    gen_squirrel()
    gen_install()
    gen_deploy()
    print("== 完成 ==")


if __name__ == "__main__":
    main()
